safety clause to check Gemfile
to make sure we don't build with libxml-ruby still in the Gemfile

diff --git a/build_all b/build_all
--- a/build_all
+++ b/build_all
@@ -15,6 +15,11 @@ else
     echo "ERROR: An RVM installation was not found.\n"
 fi
 
+if grep libxml-ruby Gemfile ; then
+  echo "ERROR: please remove the libxml-ruby line from your Gemfile"
+  exit 1
+fi
+
 set -o errexit
 set -x
 
