let's make sure we're on a 32-bit system

diff --git a/build_all b/build_all
--- a/build_all
+++ b/build_all
@@ -53,6 +53,13 @@ rm -rf gems
 mkdir -p gems
 
 # windows
+platform=$(uname -i)
+if [[ $platform =~ "64" ]] ; then
+    echo ""
+    echo "ERROR: You need to build the windows gem on a 32-bit machine!"
+    echo ""
+    exit 1
+fi
 rvm_use 1.8.7
 if [[ ! -a ${HOME}/.rake-compiler/ruby/ruby-1.8.7-p330/lib/ruby/1.8.7/x86_64-linux/rbconfig.rb ]] ; then
     bundle exec rake-compiler cross-ruby VERSION=1.8.7-p330
